name: Deploying React App on Surge

on:
  push:
    branches: [ master ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Seting-up Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12
          check-latest: true                    # will check latest version of Node.js

      - name: Installing Yarn
        uses: borales/actions-yarn@v2.0.0
        with:
          run: yarn install                     # will run `yarn install` command
 
      - name: Building React App
        run: yarn build                         # yarn will build optimized code for production
        
      - name: Installing Surge
        run: npm install --global surge         # will install surge for gloabal use

      - name: Deploying React App on Surge
        run: surge ./build http://piaic-bc2020-c002.surge.sh --token ${{ secrets.SURGE_TOKEN }}
